// In-app AI/ML glossary. ~150 entries; full-text searchable. Curated definitions.
export type GlossaryEntry = { term: string; def: string; tags: string[]; related?: string[] };

export const GLOSSARY: GlossaryEntry[] = [
  { term: "Accuracy", def: "Fraction of correct predictions out of total. Misleading for imbalanced data; use F1/PR-AUC instead.", tags: ["metric"], related: ["F1 Score","Precision","Recall"] },
  { term: "Activation Function", def: "Non-linear function applied after a layer's linear transformation. Common: ReLU, GELU, sigmoid, tanh. Without it, a deep network collapses to a single linear layer.", tags: ["deep-learning"], related: ["ReLU","GELU","Sigmoid"] },
  { term: "AdaBoost", def: "Boosting algorithm that reweights misclassified samples each round. Predecessor of XGBoost / LightGBM.", tags: ["ml"] },
  { term: "Adam", def: "Adaptive optimiser combining momentum (mean of grads) and RMSProp (variance of grads). Default for most deep learning. Update: θ ← θ − lr·m̂/√v̂.", tags: ["optim"], related: ["AdamW","SGD","RMSProp"] },
  { term: "AdamW", def: "Adam with decoupled weight decay. Outperforms Adam on Transformers; current default for LLM training.", tags: ["optim"], related: ["Adam","Weight Decay"] },
  { term: "Agent", def: "An LLM-driven loop that chooses actions (tools / functions) to achieve a goal, observes results, and iterates.", tags: ["agents"], related: ["ReAct","LangGraph","Tool Use"] },
  { term: "AGI", def: "Artificial General Intelligence — hypothetical AI matching or exceeding human cognitive ability across all domains.", tags: ["ai"] },
  { term: "Anomaly Detection", def: "Identifying rare/abnormal data points. Used in fraud, intrusion, manufacturing defects. Methods: Isolation Forest, autoencoders, one-class SVM.", tags: ["ml"] },
  { term: "Attention", def: "Mechanism where each output token attends to all input tokens via weighted softmax(QKᵀ/√d_k)·V. Backbone of Transformers.", tags: ["nlp","deep-learning"], related: ["Self-Attention","Multi-Head Attention","Flash Attention"] },
  { term: "AUC-ROC", def: "Area under the Receiver Operating Characteristic curve. Threshold-independent ranking quality metric. 0.5 = random, 1.0 = perfect.", tags: ["metric"], related: ["PR-AUC","Precision","Recall"] },
  { term: "Autograd", def: "Automatic differentiation. PyTorch / JAX / TF compute gradients by tracing forward operations and applying chain rule backward.", tags: ["deep-learning"], related: ["Backpropagation","Chain Rule"] },
  { term: "Autoencoder", def: "Neural net that learns to reconstruct its input through a bottleneck. Used for compression, denoising, anomaly detection, pretraining.", tags: ["deep-learning"], related: ["VAE","Latent Space"] },
  { term: "Backpropagation", def: "Algorithm that applies chain rule from loss back through the network to compute gradients for every parameter in a single pass.", tags: ["deep-learning"], related: ["Chain Rule","Autograd"] },
  { term: "Bag of Words", def: "Text representation as a vector of word counts. Ignores order. Baseline before word embeddings.", tags: ["nlp"], related: ["TF-IDF","Embeddings"] },
  { term: "BatchNorm", def: "Normalises a layer's activations to mean 0 / variance 1 per mini-batch. Speeds up training, allows higher LR.", tags: ["deep-learning"], related: ["LayerNorm","Group Norm"] },
  { term: "Bayes' Theorem", def: "P(A|B) = P(B|A)P(A)/P(B). Updates a prior belief P(A) with evidence B to a posterior P(A|B).", tags: ["math","prob"], related: ["Naive Bayes","Posterior"] },
  { term: "BERT", def: "Bidirectional Encoder Representations from Transformers. Masked-LM pretraining; encoder-only. Released by Google 2018.", tags: ["nlp"], related: ["GPT","Masked LM"] },
  { term: "Bias-Variance Tradeoff", def: "Total error = bias² + variance + irreducible noise. Simple models = high bias; complex = high variance. Regularisation reduces variance at cost of bias.", tags: ["ml-theory"] },
  { term: "BLEU", def: "Bilingual Evaluation Understudy. N-gram overlap metric for machine translation. Surrogate, often misleading; superseded by BERTScore / human eval.", tags: ["metric","nlp"] },
  { term: "BPE", def: "Byte-Pair Encoding. Subword tokenisation: greedily merge most-frequent byte pairs. Used in GPT, BERT.", tags: ["nlp"], related: ["Tokenization","WordPiece"] },
  { term: "Catastrophic Forgetting", def: "When fine-tuning a model on a new task degrades performance on old tasks. Mitigations: EWC, replay buffers, LoRA.", tags: ["ml"] },
  { term: "Chain Rule", def: "(f∘g)′(x) = f′(g(x))·g′(x). Backbone of backpropagation through deep networks.", tags: ["math"], related: ["Backpropagation"] },
  { term: "Chain of Thought (CoT)", def: "Prompting technique: ask the model to reason step-by-step before answering. Improves multi-step reasoning.", tags: ["llm","prompting"] },
  { term: "ChromaDB", def: "Open-source vector database for RAG. Python-first, simple API, runs locally.", tags: ["rag"], related: ["Pinecone","Qdrant","Vector Database"] },
  { term: "CLIP", def: "Contrastive Language-Image Pretraining. OpenAI 2021. Joint text-image encoder; foundation of DALL-E, Stable Diffusion guidance.", tags: ["multimodal"], related: ["Contrastive Learning"] },
  { term: "Confusion Matrix", def: "Table of TP/FP/TN/FN counts. From it derive precision, recall, F1, accuracy.", tags: ["metric"] },
  { term: "Contrastive Learning", def: "Self-supervised approach: pull positive pairs together, push negatives apart in embedding space. Powers SimCLR, CLIP.", tags: ["ssl"] },
  { term: "Convolution", def: "Sliding dot product of a kernel over input. Captures local spatial patterns. Foundation of CNNs.", tags: ["deep-learning","cv"], related: ["CNN"] },
  { term: "Cross-Entropy", def: "−Σ p(x)·log q(x). Loss for classification = NLL under categorical / Bernoulli. Equal to entropy + KL divergence.", tags: ["math","metric"], related: ["KL Divergence","Entropy"] },
  { term: "Cross-Validation", def: "K-fold: split data into K parts, train K times leaving each part as held-out. Reduces variance of model estimate.", tags: ["ml"], related: ["Stratified K-Fold"] },
  { term: "CUDA", def: "NVIDIA's parallel computing platform. All major deep learning frameworks compile to CUDA kernels for GPU acceleration.", tags: ["systems"] },
  { term: "DALL-E", def: "OpenAI's text-to-image diffusion model. Versions 2/3 use unCLIP / cascaded diffusion architectures.", tags: ["multimodal"] },
  { term: "Data Augmentation", def: "Synthetic transforms of training data (flip, crop, mixup) to improve generalisation without collecting more samples.", tags: ["ml"] },
  { term: "Data Leakage", def: "Information from test/future leaking into training. Causes optimistic CV scores that don't generalise. Common with target encoding, time-series.", tags: ["ml"] },
  { term: "Decision Tree", def: "Tree where each node splits on a feature threshold. Greedy splits maximise info gain / Gini. Building block for RF and GB.", tags: ["ml"] },
  { term: "DeepSeek", def: "Chinese open-source LLM family. R1 (2024) reasoning model demonstrated frontier-level performance at low cost via pure RL training.", tags: ["llm"] },
  { term: "Distillation", def: "Train a smaller \"student\" model to match a larger \"teacher\". Soft targets from teacher's softmax. Hinton 2015.", tags: ["llm"] },
  { term: "DPO", def: "Direct Preference Optimization. Train preference data without a separate reward model. Replaces complex RLHF + PPO loop.", tags: ["llm","rlhf"] },
  { term: "Dropout", def: "Randomly zero a fraction of activations during training. Acts as ensemble regulariser. Disabled at inference.", tags: ["deep-learning"] },
  { term: "Early Stopping", def: "Stop training when validation loss stops decreasing. Cheap regularisation.", tags: ["ml"] },
  { term: "Eigenvalue / Eigenvector", def: "Av = λv. v is the direction preserved by A (up to scaling); λ is the scale factor. Foundation of PCA, spectral methods.", tags: ["math"], related: ["PCA","SVD"] },
  { term: "Embedding", def: "Dense vector representation of tokens/images/users in continuous space. Similar items have similar embeddings.", tags: ["nlp","rag"] },
  { term: "Entropy", def: "H(X) = −Σ p·log p. Measure of uncertainty / number of bits to optimally encode samples.", tags: ["math","info"], related: ["Cross-Entropy","KL Divergence"] },
  { term: "Epoch", def: "One full pass over the training dataset.", tags: ["deep-learning"] },
  { term: "F1 Score", def: "Harmonic mean of precision and recall: 2·P·R/(P+R). Single-number summary that punishes imbalance.", tags: ["metric"] },
  { term: "FAISS", def: "Facebook AI Similarity Search. Approximate-nearest-neighbour library for vector retrieval at scale.", tags: ["rag"] },
  { term: "Few-Shot Learning", def: "Adapting a model to a new task using only a handful of labelled examples (often via prompting).", tags: ["llm"] },
  { term: "Fine-Tuning", def: "Continue training a pretrained model on a task-specific dataset. Variants: full FT, PEFT, LoRA, QLoRA.", tags: ["llm"] },
  { term: "Flash Attention", def: "I/O-aware attention algorithm that fuses softmax + matmul to avoid the O(n²) memory hit. 5–10× speedup, longer context.", tags: ["llm"] },
  { term: "GAN", def: "Generative Adversarial Network. Generator vs Discriminator zero-sum game. Powered StyleGAN; largely replaced by diffusion for images.", tags: ["deep-learning"] },
  { term: "Gemini", def: "Google's multimodal LLM family (2.5 Flash / Pro / Ultra). Native image+audio+video support, 1M+ context.", tags: ["llm"] },
  { term: "GELU", def: "Gaussian Error Linear Unit. Smooth ReLU-like activation: x·Φ(x). Used in BERT, GPT, ViT.", tags: ["deep-learning"] },
  { term: "Gradient Clipping", def: "Cap the gradient norm before optimiser step. Prevents exploding gradients in RNNs / Transformers.", tags: ["optim"] },
  { term: "Gradient Descent", def: "Iteratively step against the gradient of loss: θ ← θ − lr·∇L. Variants: SGD, Adam, RMSProp.", tags: ["optim"] },
  { term: "GraphRAG", def: "RAG variant that uses a knowledge graph extracted from documents instead of (or alongside) vector search. Microsoft 2024.", tags: ["rag"] },
  { term: "GroupNorm", def: "Normalises within groups of channels. Doesn't depend on batch size — useful for small batches / detection / video.", tags: ["deep-learning"] },
  { term: "Hallucination", def: "LLM generating confidently wrong / fabricated content. Mitigations: RAG, constrained decoding, factuality fine-tuning.", tags: ["llm"] },
  { term: "Hessian", def: "Matrix of second partial derivatives. Curvature of the loss. Used in Newton's method; expensive (d×d) for deep learning.", tags: ["math"] },
  { term: "HNSW", def: "Hierarchical Navigable Small World. Graph-based ANN structure used in Pinecone, Qdrant, Milvus.", tags: ["rag"] },
  { term: "Hugging Face", def: "Platform hosting models, datasets, demos. `transformers` library is the de-facto NLP/CV inference stack.", tags: ["llm"] },
  { term: "HyDE", def: "Hypothetical Document Embeddings. RAG technique: use the LLM to generate a hypothetical answer; embed THAT for retrieval.", tags: ["rag"] },
  { term: "Imbalanced Data", def: "When class proportions differ greatly. Fixes: class weights, oversampling (SMOTE), undersampling, threshold tuning, PR-AUC.", tags: ["ml"] },
  { term: "Inference", def: "Running a trained model on new input to produce predictions. Distinct from training.", tags: ["systems"] },
  { term: "JAX", def: "Google's NumPy-like functional autodiff library. Composes grad, jit, vmap, pmap. Used in Flax / Haiku research.", tags: ["systems"] },
  { term: "K-Means", def: "Cluster N points into K groups by minimising within-cluster squared distance. Alternates assignment + centroid update.", tags: ["ml"] },
  { term: "KL Divergence", def: "KL(p‖q) = Σ p·log(p/q). Measure of how p differs from q. Asymmetric; ≥ 0; foundation of VAE, RLHF, distillation.", tags: ["math","info"] },
  { term: "KNN", def: "K-Nearest Neighbours. Lazy learner: predict by majority/average of K closest training points.", tags: ["ml"] },
  { term: "LangChain", def: "Python framework for chaining LLM calls, tools, memory. Most popular agent + RAG toolkit.", tags: ["llm","agents"] },
  { term: "LangGraph", def: "Graph-based agent framework from LangChain. Explicit state machines + cycles for complex agents.", tags: ["agents"] },
  { term: "LayerNorm", def: "Normalises across features (not batch). Default in Transformers; works with any batch size.", tags: ["deep-learning"] },
  { term: "LightGBM", def: "Gradient boosting library from Microsoft. Faster than XGBoost on big data via histogram-based splits.", tags: ["ml"] },
  { term: "LLaMA", def: "Meta's open-weights LLM family (1/2/3/3.1). Foundation for thousands of fine-tunes.", tags: ["llm"] },
  { term: "LoRA", def: "Low-Rank Adaptation. Fine-tune a model by adding rank-r matrices ΔW = BA to frozen W. 100-1000× fewer trainable params.", tags: ["llm"] },
  { term: "Loss Function", def: "Scalar function we minimise: MSE, cross-entropy, contrastive, etc. Defines what \"learning\" means.", tags: ["ml"] },
  { term: "MCP", def: "Model Context Protocol. Anthropic 2024 standard for connecting LLMs to tools / data sources.", tags: ["agents"] },
  { term: "Memorisation vs Generalisation", def: "A model memorises if train acc >> test acc; generalises if both are close. The whole game.", tags: ["ml-theory"] },
  { term: "MLflow", def: "Experiment tracker + model registry. Logs params, metrics, artifacts; standard MLOps tool.", tags: ["mlops"] },
  { term: "MLOps", def: "Engineering practices for productionising ML: CI/CD, monitoring, drift detection, model registry.", tags: ["mlops"] },
  { term: "MLP", def: "Multilayer Perceptron. Fully-connected feedforward net with at least one hidden layer.", tags: ["deep-learning"] },
  { term: "Momentum", def: "Optimisation trick: average past gradients with EMA. Smooths trajectory and accelerates flat regions.", tags: ["optim"] },
  { term: "Mixture of Experts (MoE)", def: "Architecture with many specialised subnetworks; a router selects k experts per token. Scales params without scaling compute.", tags: ["llm"] },
  { term: "Multi-Head Attention", def: "Run attention in h parallel \"heads\" with different projections, then concatenate. Lets the model attend in multiple subspaces.", tags: ["nlp"] },
  { term: "Naive Bayes", def: "Probabilistic classifier assuming features are conditionally independent. Surprisingly strong baseline for text.", tags: ["ml"] },
  { term: "NER", def: "Named Entity Recognition. Tagging text spans as Person/Org/Location/Date.", tags: ["nlp"] },
  { term: "Normalisation", def: "Scaling features. StandardScaler (z-score), MinMax, RobustScaler. Critical for distance-based and gradient-based methods.", tags: ["ml"] },
  { term: "One-Hot Encoding", def: "Categorical → binary vector. Each category gets its own column. Use OneHotEncoder; avoid for high-cardinality features.", tags: ["ml"] },
  { term: "Optimiser", def: "Algorithm that uses gradients to update parameters. SGD, Momentum, RMSProp, Adam, AdamW, Lion, Adafactor.", tags: ["optim"] },
  { term: "Overfitting", def: "Model fits noise in training data, fails on new data. Fixes: more data, regularisation, dropout, early stopping.", tags: ["ml"] },
  { term: "PCA", def: "Principal Component Analysis. Project data onto directions of maximum variance via eigendecomposition (or SVD) of covariance.", tags: ["ml","math"] },
  { term: "PEFT", def: "Parameter-Efficient Fine-Tuning. Umbrella: LoRA, QLoRA, prefix tuning, adapters. Fine-tune ≤ 1% of params.", tags: ["llm"] },
  { term: "Pinecone", def: "Managed vector DB. Built-in HNSW, metadata filtering, hybrid search.", tags: ["rag"] },
  { term: "Polars", def: "Rust-backed DataFrame library; 5-10× faster than Pandas on large tabular data. Lazy execution.", tags: ["tools"] },
  { term: "PPO", def: "Proximal Policy Optimization. RL algorithm; OpenAI's default for RLHF. Clips policy updates to stay near previous policy.", tags: ["rl"] },
  { term: "PR-AUC", def: "Precision-Recall AUC. Better than ROC-AUC for imbalanced classification — focuses on the positive class.", tags: ["metric"] },
  { term: "Precision", def: "TP / (TP + FP). Of predicted positives, how many were correct? Cares about false alarms.", tags: ["metric"] },
  { term: "Prompt Engineering", def: "Designing input prompts to elicit desired LLM behavior. Patterns: zero/few-shot, CoT, ReAct, structured output.", tags: ["llm"] },
  { term: "PyTorch", def: "Meta's deep learning framework. Default for research. Eager execution + compiled via torch.compile.", tags: ["deep-learning"] },
  { term: "QLoRA", def: "Quantized LoRA. 4-bit base model + LoRA adapters. Fine-tunes 65B model on single GPU. Dettmers 2023.", tags: ["llm"] },
  { term: "Quantization", def: "Convert fp32 weights to int8/int4. Smaller / faster inference at modest quality cost. Methods: GPTQ, AWQ, GGUF.", tags: ["llm"] },
  { term: "RAG", def: "Retrieval-Augmented Generation. Retrieve relevant docs first, then condition the LLM on them. Reduces hallucination.", tags: ["rag"] },
  { term: "RAGAS", def: "Open-source RAG evaluation library. Metrics: faithfulness, answer relevance, context precision/recall.", tags: ["rag"] },
  { term: "Random Forest", def: "Ensemble of decision trees trained on bootstrap samples + random feature subsets. Reduces variance.", tags: ["ml"] },
  { term: "ReAct", def: "Reason + Act prompting pattern. LLM alternates thought / action / observation in a loop. Foundation of most agents.", tags: ["agents"] },
  { term: "Recall", def: "TP / (TP + FN). Of all real positives, how many did we catch? Cares about misses.", tags: ["metric"] },
  { term: "Regularisation", def: "Penalising model complexity to prevent overfitting. L1 (Lasso), L2 (Ridge), dropout, weight decay.", tags: ["ml"] },
  { term: "ReLU", def: "Rectified Linear Unit: max(0, x). Default activation. Solved the vanishing gradient problem of sigmoid.", tags: ["deep-learning"] },
  { term: "Residual Connection", def: "Skip connection: y = F(x) + x. Foundation of ResNet; lets gradients flow through arbitrarily deep nets.", tags: ["deep-learning"] },
  { term: "RLHF", def: "Reinforcement Learning from Human Feedback. SFT → reward model → PPO. Aligns LLM outputs with human preferences.", tags: ["llm"] },
  { term: "RNN", def: "Recurrent Neural Network. Processes sequences token by token, maintaining a hidden state. Largely replaced by Transformers.", tags: ["nlp"] },
  { term: "ROC Curve", def: "True positive rate vs false positive rate as threshold varies. Area = AUC-ROC.", tags: ["metric"] },
  { term: "RoPE", def: "Rotary Position Embedding. Encodes position via 2D rotation of query/key pairs. Used in LLaMA, GPT-NeoX.", tags: ["llm"] },
  { term: "Sampling", def: "Drawing tokens from the LLM's softmax distribution. Temperature, top-k, top-p (nucleus) control diversity.", tags: ["llm"] },
  { term: "Self-Attention", def: "Attention where queries, keys, values all come from the same input. The core of Transformers.", tags: ["nlp"] },
  { term: "SGD", def: "Stochastic Gradient Descent. Update parameters using gradient of one (or a mini-batch) sample. Noisy but escapes saddles.", tags: ["optim"] },
  { term: "Sigmoid", def: "σ(x) = 1/(1+e⁻ˣ). Maps to (0,1). Used for binary output / gates. Replaced by ReLU/GELU in hidden layers.", tags: ["deep-learning"] },
  { term: "Softmax", def: "Converts logits to probabilities: σ(zᵢ) = exp(zᵢ) / Σ exp(zⱼ). Standard final layer for multi-class.", tags: ["deep-learning"] },
  { term: "SQL", def: "Structured Query Language. Tabular data manipulation. Mandatory for any ML engineer role.", tags: ["tools"] },
  { term: "Stable Diffusion", def: "Open-source latent diffusion model for text-to-image. Versions 1.5, XL, 3, FLUX. CompVis / Stability AI.", tags: ["multimodal"] },
  { term: "SVM", def: "Support Vector Machine. Find hyperplane that maximises margin between classes. Kernels handle non-linear decisions.", tags: ["ml"] },
  { term: "TF-IDF", def: "Term Frequency × Inverse Document Frequency. Classic text vectoriser. Still useful as a baseline.", tags: ["nlp"] },
  { term: "Tokenization", def: "Splitting text into model-input units. Word, character, subword (BPE/WordPiece/SentencePiece). Foundation of every NLP model.", tags: ["nlp"] },
  { term: "Top-k Sampling", def: "Sample only from the k highest-probability tokens. Limits low-quality tail.", tags: ["llm"] },
  { term: "Top-p (Nucleus)", def: "Sample from smallest set of tokens whose cumulative probability ≥ p. Adapts vocabulary size to distribution.", tags: ["llm"] },
  { term: "Transformer", def: "Architecture using only attention + feedforward. Vaswani et al 2017. Backbone of all modern LLMs and many vision models.", tags: ["deep-learning"] },
  { term: "Triton (NVIDIA)", def: "NVIDIA's inference server for high-throughput serving of TF/PyTorch/ONNX models.", tags: ["mlops"] },
  { term: "Triton (OpenAI)", def: "Python-like DSL for writing GPU kernels. Foundation of Flash Attention and many custom kernels.", tags: ["systems"] },
  { term: "VAE", def: "Variational Autoencoder. Encoder outputs Gaussian parameters of a latent; decoder reconstructs. Loss = recon + KL to prior.", tags: ["deep-learning"] },
  { term: "Vanishing Gradient", def: "Gradients shrink to ~0 through deep networks (esp. with sigmoid/tanh). Solutions: ReLU, residual connections, LayerNorm.", tags: ["deep-learning"] },
  { term: "Vector Database", def: "Storage + ANN-search engine for high-dim embeddings. Examples: Pinecone, Chroma, Qdrant, Milvus, Weaviate.", tags: ["rag"] },
  { term: "Vertex AI", def: "Google Cloud's managed ML platform: training, serving, Gemini API, AutoML, Agent Builder.", tags: ["mlops"] },
  { term: "ViT", def: "Vision Transformer. Treat image as a sequence of patches; apply standard Transformer. Dosovitskiy 2020.", tags: ["cv"] },
  { term: "vLLM", def: "High-throughput LLM inference server. PagedAttention manages KV-cache memory. State of the art.", tags: ["mlops"] },
  { term: "Weight Decay", def: "L2 regularisation as part of optimiser step: θ ← θ − lr·∇L − lr·λ·θ. Pulls weights toward zero.", tags: ["optim"] },
  { term: "Word2Vec", def: "Mikolov 2013. CBOW + Skip-gram. First widely-used word embeddings. Superseded by contextual embeddings (ELMo, BERT).", tags: ["nlp"] },
  { term: "XGBoost", def: "Extreme Gradient Boosting. Second-order Taylor + L1/L2 reg + smart tree growth. Default winner of tabular Kaggle.", tags: ["ml"] },
  { term: "Zero-Shot", def: "Solving a task with no task-specific training examples — just a prompt. Capability emerges in large LMs.", tags: ["llm"] },
];

export function searchGlossary(q: string): GlossaryEntry[] {
  const query = q.trim().toLowerCase();
  if (!query) return GLOSSARY;
  return GLOSSARY.filter((e) =>
    e.term.toLowerCase().includes(query) ||
    e.def.toLowerCase().includes(query) ||
    e.tags.some((t) => t.toLowerCase().includes(query))
  );
}
