import { prisma } from "@/lib/prisma";
import FlashcardReviewer from "@/components/FlashcardReviewer";

export const dynamic = "force-dynamic";

export default async function FlashcardsPage() {
  const due = await prisma.flashcard.findMany({
    where: { nextDue: { lte: new Date() } },
    include: { topic: { select: { code: true, title: true, id: true } } },
    orderBy: { nextDue: "asc" },
    take: 50,
  });

  return (
    <div className="space-y-6 animate-[fadeInUp_0.5s_ease-out]">
      <header>
        <div className="text-xs uppercase tracking-[0.25em] text-text-muted mb-2">Spaced Repetition</div>
        <h1 className="text-4xl font-extrabold gradient-text">{due.length} cards due</h1>
        <p className="text-text-secondary mt-2">SM-2 algorithm. Rate honestly. Cards are generated by Gemini on topic pages.</p>
      </header>

      {due.length === 0 ? (
        <div className="glass p-10 text-center">
          <div className="text-text-secondary">No cards due right now.</div>
          <div className="text-xs text-text-muted mt-2">Open a topic → Gemini panel → "Generate flashcards".</div>
        </div>
      ) : (
        <FlashcardReviewer cards={due.map((c) => ({
          id: c.id, q: c.question, a: c.answer,
          topicCode: c.topic.code, topicTitle: c.topic.title, topicId: c.topic.id,
        }))} />
      )}
    </div>
  );
}
